**Project ID:** [plumID:23.026]({{ '/' | absolute_url }}eggs/23/026/)  
Stderr for source:  plumed_model_2D_WTD.dat   
Download: [zipped raw stdout](plumed_model_2D_WTD.dat.plumed.stdout.txt.zip) - [zipped raw stderr](plumed_model_2D_WTD.dat.plumed.stderr.txt.zip) 
{% raw %}
<pre>
#! Only the first 1000 rows of the error file are shown below
#! To inspect the full error file, please download the zipped raw stderr file above
terminate called after throwing an instance of 'PLMD::Plumed::Exception'
what():
Action "PYTHONCV" is not known.
[fv-az1945-156:07011] *** Process received signal ***
[fv-az1945-156:07011] Signal: Aborted (6)
[fv-az1945-156:07011] Signal code:  (-6)
[fv-az1945-156:07011] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7f5258245330]
[fv-az1945-156:07011] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11c)[0x7f525829eb2c]
[fv-az1945-156:07011] [ 2] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x1e)[0x7f525824527e]
[fv-az1945-156:07011] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xdf)[0x7f52582288ff]
[fv-az1945-156:07011] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5ff5)[0x7f52586a5ff5]
[fv-az1945-156:07011] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb0da)[0x7f52586bb0da]
[fv-az1945-156:07011] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt10unexpectedv+0x0)[0x7f52586a5a55]
[fv-az1945-156:07011] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5a6f)[0x7f52586a5a6f]
[fv-az1945-156:07011] [ 8] plumed(+0x146dd)[0x56193ffa96dd]
[fv-az1945-156:07011] [ 9] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7f525822a1ca]
[fv-az1945-156:07011] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7f525822a28b]
[fv-az1945-156:07011] [11] plumed(+0x15365)[0x56193ffaa365]
[fv-az1945-156:07011] *** End of error message ***
</pre>
{% endraw %}
